### ISSUE TITLE
Return full image instead of thumbnail

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-earthengine-driver#15]
It would be great if the full image would be returned instead of a thumbnail as a result of a completed job.

**Comment by m-mohr** [comment]
I just tried to use `getDownloadUrl` instead of `getThumbsUrl`. Unfortunately, I never managed to get a download URL from Google. I think I am following the documentation and tried a lot of combinations and values. There are no error messages returned, just an empty download URL returned so it's very hard to find out what is going wrong there. 

Google suggests to not use `getDownloadUrl` anyway, they prefer us to use Export.toDrive/toCloudStorage/toAssets. We can't use GCS as we don't have a credit card, I'm not sure how to download assets and I don't have time at the moment to dig into the Drive API. So it seems there's nothing I can improve here in the next weeks.

What I can offer is that I increase the preview image size from 512px to let's say 2000px? Would that help for now?

**Comment by Sijoma** [comment]
Yes that would be better. Thanks.

**Comment by m-mohr** [comment]
The preview endpoint now generates 1000px, batch jobs generare 2000px instead of 512px.

**Comment by m-mohr** [comment]
We have now basic support for two types of GeoTiffs:

- zipped, larger size GeoTiffs (GTIFF-ZIP)
- smaller size GeoTiffs (GTIFF-THUMB)

I'm thinking to unzip the files in batch jobs for convenience.

No cloud optimized GeoTiffs at the moment as we use a legacy API (getThumbUrl/getDownloadUrl). GEE batch export is another step for the future, which supports cloud optimized files. There's some code already in a branch, but I haven't had time to look into the Google Drive issues.
