### ISSUE TITLE
mask process has no replacement value

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-earthengine-driver#52]
I see some news in various processes using in the latest Web Editor (used with GEE backed):
1. merge_cubes doesn't have overlap_resolver anymore, which is good since it never worked
2. mask is missing the replacement value. Did the process definition change? Is it set to zero or Nan by default? We need it for an if-else condition for our use case.

Cheers,
Michele

**Comment by m-mohr** [comment]
Likely not a Web Editor issue, but a GEE issue. 

1. Yes, we updated merge_cubes to not have the overlap_resolver anymore. 
2. mask hasn't changed in GEE since June, but it never had the replacement value implemented yet. So that's something that still needs to be implemented. @bgoesswe What do you think: How much work would that be?

**Comment by m-mohr** [comment]
I just implemented the replacement value.  Will update the public instance after PR #56 has been reviewed and merged.

**Comment by m-mohr** [comment]
Has been deployed @clausmichele
