### ISSUE TITLE
how to connect with Google Earth Engine 

### ISSUE THREAD

**Issue by jome1** [Open-EO/openeo-earthengine-driver#91]
Dear Community,

I want to connect to the Google Earth Engine via the python openeo API. The [documentation](https://openeo.org/documentation/1.0/python/#processes) is not detailed enough for this.

The Google Earth Engine implementation for openEO only supports Basic authentication. So you would use the following code for the connection:
```
import openeo

connection = openeo.connect("https://earthengine.openeo.org")
connection.authenticate_basic("username", "password")
```

Which username and password do I have to use? 
The documentation refers to this [link](https://github.com/Open-EO/openeo-earthengine-driver#demo). There is a link to [register for GEE](https://signup.earthengine.google.com/). But then I only create a new cloud project with my google account.
Using my google mail address and my password in the code above for the connection does not work.

I know it is not production-ready. But since the documentation uses GEE as an example, I thought it might be worth a try.

**Comment by m-mohr** [comment]
Hey,

since recently you can also connect via OpenID Connect and then use your Google Account to login, but you'd need to get a client ID and client secret from Google first.

If you just want to test it quickly, you can use our demo accounts.
Usernames are `group1`, `group2`, `group3`, etc. (Just choose one, there might be data from other users already as these credentials are public).
Password is `test123`.

Hope this helps.

**Comment by jome1** [comment]
Thanks a lot for the info!
